name: my workflow

on: push

jobs:
  my-first-job:
    runs-on: windows-latest
    steps:
      - name: Print Hello World
        run: echo "Hello world"

  my-second-job:
    runs-on: windows-latest
    steps:
      - name: Print Hi, This is pallavi
        run: echo "Hi, This is pallavi"