name: 02- workflow-events

on: 
  push:
  pull_request:
  schedule:
     - cron: '*/5 * * * *'
  workflow_dispatch:


jobs:
  echo:
    runs-on: windows-latest
    steps:
      - name: "Show the Trigger"
        run: echo "This workflow was triggered by a push event"
